### ISSUE TITLE
Adding a new crew member

### ISSUE THREAD

**Issue by xYuchi** [xYuchi/xyuchi.github.io#4]
Dear @falceso, and @mysteriace.

I might add the Collarbator, @MicahManlapeg because of his coding skills and 
how he does his socializing. Visit https://github.com/MicahManlapeg/Project-2789
That website contains a lot of programming languages for that repository.

Does anyone think that we should add him to http://xyuchi.github.io?

**Comment by xYuchi** [comment]
Sorry for all those messages up there ^^ -- ignore them..

**Comment by falceso** [comment]
Hmm Seems Legit..
 Also @xyuchi check out the eh development website.  :)

**Comment by xYuchi** [comment]
Sweet!

But lets be on topic about the issue :)

**Comment by falceso** [comment]
How do i see jow the project works?

**Comment by xYuchi** [comment]
"How do i see how the project works?"

idk lol

**Comment by xYuchi** [comment]
I'm going to ask him his age and if he can make something with Ruby. (PM'ing him)

**Comment by xYuchi** [comment]
Oops, closed it.. Then reopened it.

**Comment by xYuchi** [comment]
Dang.. He'is HECKA young, he's 10..

**Comment by xYuchi** [comment]
I'm adding him -- i might remove him; please create a new issue again if you want.
